name: build-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          cd ${{ github.workspace }}
          g++ -I. -L. -v -Wall -Werror -Wno-unknown-pragmas -Wno-sign-compare *.cpp -o main.exe