name: C++ Build with Clang

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Clang
        uses: actions/setup-clang@v13
        with:
          clang-version: '12'

      - name: Build C++ Project
        run: |
          mkdir build
          cd build
          cmake ..
          make
